### ISSUE TITLE
[PM] Project plan & meeting notes

### ISSUE THREAD

**Issue by dohafernandez** [Green-Software-Foundation/software_carbon_intensity_data#20]
Link to the docusaurus: https://sci-data.greensoftware.foundation/
Link to editor: https://github.dev/Green-Software-Foundation/sci-data
Srini [FAQ](https://docs.google.com/document/d/1clFzjGuPA0Vte1yo1LVltZRtuCcxM9f-aPoz0mlhSB4/edit)

How to point people to the exact data set

- [x] Decide which data source and tools do we want?
- [x] Structure all data and where to get it

Eg. Climatiqua.io   - data explorer
Boavitza - have the data in a common format

(Emissions of a managed database)

FAQ 
- how to calculate
- direct it to data sources we collaborate with

Srini's suggestion

- [x] Folders for each value SCI = ((E * I) + M) per R

Where:
E = Energy consumed by a software system (ie. How much electricity did it use)
I= Location-based marginal carbon emissions (ie. How much of the energy came from renewable/low carbon sources)
M = Embodied emissions of a software system (ie. How much hardware did you use (M))
R = Functional unit (e.g. carbon per additional user, API-call, ML job, etc)

- [ ] Add search-ability function
- [ ] Proposed SCI score folders

Overall: 
- [ ] Need a process for how data & info gets approved/reviewed
-> Issues
-> Discussion
-> PR to add (md file)
-> initial review if its correct
-> SME review
-> Team consensus
-> Consistency review

Goal: Unifying framework for data set

**Comment by jawache** [comment]
- [ ] We need a Getting Started Guide section in the main index.
-> Ask questions about data and how to calculate SCI in discussions
-> How to read the website.
-> Pointers to SCI
-> How to ask for help if it's NOT already included in the FAQ


**Process for approval**
-> PR to add content into main branch
-> Initial review if its correct by one other team member.
-> Technical author review.
-> Standards workgroup review (2 week comment and review, if no objections auto merge)
-> Merge PR

**Comment by dohafernandez** [comment]
Link to the docusaurus: https://sci-data.greensoftware.foundation/
Link to editor: https://github.dev/Green-Software-Foundation/sci-data
Srini [FAQ](https://docs.google.com/document/d/1clFzjGuPA0Vte1yo1LVltZRtuCcxM9f-aPoz0mlhSB4/edit) 

Question: how to link the data into the page from external parties like Boavitza 

**Comments**
Navveen Balani:
_We can start with FAQ to unblock people. Secondly, we could look at how to build a unified data model, sourced from multiple providers_

Srini: _Process for review needs to be different than patterns because anyone reviewing it might not have additional information compared to Navveen and Srini._ 

- [x] Asim to ensure Srini and Navveen have permissions 

- [x] Check Patterns regarding the get started guide

This is a Maintainer based project for now.  

This project will sit under Standard's working group that will review it. So PR will be reviewed during the meetings. 

Start the process to get the standard working group to review. 

- [x] @srini1978 and @navveenb to sync up and split up the work 

Srini is OOO until 11th October

**Comment by dohafernandez** [comment]
The approach is to add all the information and then structure the navigation.

@srini1978  tasks:
- [x] Getting started folder
- [x] Input the information for **E** in folder
- [x] Add 4 approaches/frameworks to calculate **E** 

@Navveen tasks:
- [x] Input the information for **I** in folder

@dohafernandez task:
- [x] Review the [FAQ doc] with the information added to the page (https://docs.google.com/document/d/1clFzjGuPA0Vte1yo1LVltZRtuCcxM9f-aPoz0mlhSB4/edit) 
- [x] set up next meetings

Some will be FAQs and some will be data sets

Carbon api -https://cloud.google.com/carbon-footprint/docs/api

**Comment by dohafernandez** [comment]
On behalf of @srini1978 
I have made edits to the SCI open data page 
based on our discussion - created a kind of hierarchy
Consolidated all changes for "E" and deployed it
[https://sci-data.greensoftware.foundation/E/](https://sci-data.greensoftware.foundation/E/)


@navveenb Please review

**Comment by navveenb** [comment]
I have added details and structure to I, M and R and added more details for E.
https://sci-data.greensoftware.foundation/

**Comment by dohafernandez** [comment]
Structure and content is already there and now the next step is iteration. We need technical edit review and add details and resources. 

@navveenb: its ready for COP but needs a bit of polishing. We need a welcome page explaining how to navigate and use the open data and calculate. Simple use cases to show the navigation.

@srini1978  to review it and suggest edits but based on what we are seeing today, he doesnt believe it will need any restructuring. Just polishing. 

Discussion regarding the review process. Standards working group is on Thursday. Navveen suggests adding it to the SWG's agenda. 

@jawache questions for you: Where does this project lie, whether its open source or standards WG? How much time does the SWG need to review?

Action:
- [x] @srini1978  to review and polish
- [x] @navveenb & @srini1978  add welcome page
- [x] @dohafernandez book a technical editor for the week of the 20th 

Navveen 24,25,26 OOO

**Comment by navveenb** [comment]
Created Getting started page and populated contents - https://sci-data.greensoftware.foundation/GettingStarted/

**Comment by dohafernandez** [comment]
On behalf of @navveenb 

Quick updates –
I have created the Getting Started Page - https://sci-data.greensoftware.foundation/GettingStarted/ which provide details on how to use the SCI Data and a sample use case for SCI score calculation which uses the SCI Open Data contents.
Added more details and structure for E, I, M and R

Srini, please review and feel free to edit and commit to the document.

We are in good shape for SCI Open Data and mostly all contents are available.

As a next step, once Srini completes the review, we can involve a technical writer for technical edits and format changes.

**Comment by dohafernandez** [comment]
I have reached out to Catherine, the technical writer to confirm her availability to do the edits. She is currently OOO so I will update here once I have a response.

**Comment by dohafernandez** [comment]
Catherine is available and will take 1 week to work on this. 
What format can she access to edit it? She says she cant access our GH repo @jawache

**Comment by zanete** [comment]
@dohafernandez as we spoke today in the retro, what would be needed for Catherine to be able to create a GitHub account and give us her username so we can add her to the repo? Is there something standing in the way of that?

**Comment by dohafernandez** [comment]
@zanete I asked her to clarify why she hasnt been able to access GH. Waiting for her response and will let you know as soon as I hear back. My understanding is that she has used GH before. Lets see what she says. Would be great to have on board so we can tag her in tasks as well.

**Comment by dohafernandez** [comment]
**Meeting:**
- Content is in place. Asim is happy with the content but suggests to have actual content in places where there are link. Something that can be done in the next stage.
- Asim suggested a name change but the team feel the name represents the project as we are dealing with open data sets. 
- Asim clarified that the project lies in the Standards working group (not Open source).

**Update:**
There is a SCI FAQ that has been started by the Standard working group. 
We need a consensus view by the SWG on what they want to happen with the FAQ and the SCI open data project. 
If the projects are merged, there needs to be clarity on what & where content is allowed to be added. 
Srini and Navveen will join the SWG call tomorrow Thursday 20th to discuss. 


**Review process:**
- We need to come up with the review process. 
- It takes 1-2 weeks max plus a consistency review. (Maybe we can do 1 week review + 1 week consistency review)
- This can be run as a maintainer based project. 
- We need a process by which if you reject something, the rejection can be defended. In order to eliminate any bias. 


**Next steps**
- [x] Doha to copy content into a google doc (LINK)
- [x] Catherine to start editing Monday 21st for 1 week (NO COPY CHANGES WHILE UNDER REVIEW)
- [x] @srini1978  to contact Sean to add the project onto the SWG agenda for Thursday 27th. 
- [x] @srini1978  & @navveenb  to update me on the decision made at the SWG on the 27th. (merge or not merge projects)
- [x] Update NEXT steps from the SWG decision
- [x] Navveen & Srini to create review process while Catherine edits the doc

cc @jawache

**Comment by dohafernandez** [comment]
Copied the content from SCI Data [site](https://sci-data.greensoftware.foundation/) into this [google doc](https://docs.google.com/document/d/1Tvsca3gbuZmJn-aGO4w7loxl6B23XLclEKpOaJBDIso/edit#heading=h.8c1qudhj3jc8). 
Catherine will start editing the document with Thursday 27th deadline to complete.

**Comment by dohafernandez** [comment]
@srini1978 & @navveenb the editor has edited the copy in the [doc](https://docs.google.com/document/d/1Tvsca3gbuZmJn-aGO4w7loxl6B23XLclEKpOaJBDIso/edit#heading=h.8c1qudhj3jc8)

Can either of you please review the document and accept/reject changes?

**Comment by dohafernandez** [comment]
Outcome of the SWG meeting is to have a call with Henry to discuss the Guidance & Open data set project and how to merge the two projects and what will be kept separate. 
The Guidance project will contain all of the current content but we will decide what to keep in the SCI Open data. 

**Need Clarification**
- [x] Question for Sean, is there a way to import content quickly. 
- [ ] Need to build governance around how to maintain the repo.
- [ ] Is SCI guidance the same project as Open data set project?

**Next Steps**
- [ ] Book a call with Henry (after COP) to discuss the guidance and how to maintain that
- [x] Update the content from the edited doc into GH (Doha post Hackathon)
- [x] Add tab for review process (@srini1978)
- [x] Add suggested review process for next week (all of us)
- [x] Resolve technical comments on the doc (@srini1978)

**Comment by dohafernandez** [comment]
NEXT WEEK:
**Guidance as a subproject within standards**
- [ ] Do we take care of the review process for guidance? Who owns it? What is the process?
- [x] How do we move the content over to guidance (ask Sean), repo permissions

**Comment by dohafernandez** [comment]
**Meeting notes from call 23-Nov:** 
Struggle getting people to 2 sub domains. Most/all content will be moved to guidance and we will rename the page to Guidance and delete the other one (empty guidance page). 
Note: Srini would like to have a separate location for data sources at a later point The [Universal Software Carbon Measurement](https://docs.google.com/document/d/1Tyz6vzgGkOOOkrQ705Jw_AGO7NThSPnNeN-bFwtnV1g/edit#heading=h.7ojawl556l0t) can become the one trusted source for data and maybe the data sources can be a part of this project. 

Could be a next year's hackathon project. Asim to mention this in the SWG. 

@srini1978 to create the skeleton for the review process.

**Comment by dohafernandez** [comment]
@srini1978 @navveenb I have copied all the content over. Please review it.
The order of the subfolders doesnt match the order in which the document is set out in. I dont know how to rearrange it. Can you please help me with that. 
We also need to add a folder named 'Review Process" please.

**Comment by dohafernandez** [comment]
**Meeting notes from call 1-Dec:**
- Went through Srini's suggested[ review process](https://docs.google.com/document/d/17bl6J82D-6JwK1kS8T_zSgPPIi56ye5ljfRRYfFSpzk/edit#) and agreed on it.
- Team agreed that we will have one page (subdomain) with sub folders for guidance, data, review etc.  
- I (Doha) added the content to the project page.
- Srini and Navveen to discuss the process with the WG.
- Doha to speak to Sean about migrating/renaming the page to SCI guidance.

@srini1978 @navveenb
